path:
  augmentation: /data/ephemeral/level2-cv-semanticsegmentation-cv-06-lv3/smp/configs/aug_cfg/base.yaml
  data: /data/ephemeral/level2-cv-semanticsegmentation-cv-06-lv3/smp/configs/data_cfg/1024x1024.yaml
  model: /data/ephemeral/level2-cv-semanticsegmentation-cv-06-lv3/smp/configs/model_cfg/unetplusplus_efficientnet-b7.yaml
  loss: /data/ephemeral/level2-cv-semanticsegmentation-cv-06-lv3/smp/configs/loss_cfg/dice_bce.yaml
  util: /data/ephemeral/level2-cv-semanticsegmentation-cv-06-lv3/smp/configs/util_cfg/base.yaml
  train: /data/ephemeral/level2-cv-semanticsegmentation-cv-06-lv3/smp/configs/train_cfg/base.yaml

filename: "test"