# this is config file for ensemble_inference

# csv file paths for ensemble
csv_paths: [
  'path1',
  'path2',
  'path3',
]

# ensemble result csv filename ({save_filename}_{datetime}.csv)
save_filename: test