# configs/train_cfg/base.yaml

optimizer:
  name: Adam
  lr_backbone: 1e-5
  params:
    lr: 1e-4
    weight_decay: 1e-6

scheduler:
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 100          
    T_mult: 2        # 2
    eta_min: 0.000001

trainer:
  max_epochs: 300
  check_val_every_n_epoch: 5
  accelerator: gpu
  devices: 1

callbacks:
  earlystopping:
    enabled: True
    params:
      monitor: avg_dice_score
      patience: 5
      mode: max
  model_checkpoint:
    enabled: True
    params:
      monitor: avg_dice_score
      save_top_k: 3
      mode: max

logger:
  tensorboard: True
  wandb: True
  project: unetplusplus
  name: efficientnet-b7_1024x1024 # {arch}_{encoder}_{experiements}
