# configs/model_configs/unet_efficientnet.yaml

model:
  arch: "UPernet"
  encoder_name: "efficientnet-b7"
  encoder_weights: "imagenet"
  in_channels: 3
  classes: 29

loss:
  use_combined_loss: False
  name: DiceLoss
  args:
    mode: multilabel
    smooth: 0.1


