path:
  augmentation: /data/ephemeral/hbis/configs/augmentation_configs/base_augmentation.yaml
  data: /data/ephemeral/hbis/configs/data_configs/xray_data.yaml
  model: /data/ephemeral/hbis/configs/model_configs/unet_efficientnet.yaml

optimizer:
  name: Adam
  lr_backbone: 1e-5
  params:
    lr: 1e-4
    weight_decay: 1e-6

scheduler:
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 10          
    T_mult: 1        
    eta_min: 0.000001

trainer:
  max_epochs: 100
  check_val_every_n_epoch: 5
  accelerator: gpu
  devices: 1

callbacks:
  earlystopping: True
  earlystopping_params:
    monitor: avg_dice_score
    patience: 3 # 15epoch (bc: val_interval=5)
    mode: max
  model_checkpoint: True
  model_checkpoint_params:
    monitor: avg_dice_score
    save_top_k: 3
    mode: max

logger:
  use_tensorboard: True
  use_wandb: True
  project: test
  name: upernet_efficientnet-b7_flip # {arch}_{encoder}_{experiements}


seed: 42  # 시드 값 추가
